# Generated by Django 6.0.2 on 2026-02-28 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'tipos_cuenta',
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_cuenta', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='clientes.cliente')),
                ('tipo_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='cuentas.tipocuenta')),
            ],
            options={
                'db_table': 'cuentas',
            },
        ),
    ]
